// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO4Tdc0F_yVPnIr6crcM4rWVOQ1GfkPe4',
    appId: '1:173918995139:web:7f8ab03192e0b2d1869876',
    messagingSenderId: '173918995139',
    projectId: 'my-chat-e7416',
    authDomain: 'my-chat-e7416.firebaseapp.com',
    databaseURL: 'https://my-chat-e7416-default-rtdb.firebaseio.com',
    storageBucket: 'my-chat-e7416.appspot.com',
    measurementId: 'G-2NG3MKNGY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBjBPS14ycFZSrO_T4pUqReGM9dU_45w',
    appId: '1:173918995139:android:2296058384c22bd0869876',
    messagingSenderId: '173918995139',
    projectId: 'my-chat-e7416',
    databaseURL: 'https://my-chat-e7416-default-rtdb.firebaseio.com',
    storageBucket: 'my-chat-e7416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOr9ZRflW21jKV0xMvw8RnVMl9izr_iMI',
    appId: '1:173918995139:ios:4c7ce841b866c708869876',
    messagingSenderId: '173918995139',
    projectId: 'my-chat-e7416',
    databaseURL: 'https://my-chat-e7416-default-rtdb.firebaseio.com',
    storageBucket: 'my-chat-e7416.appspot.com',
    androidClientId: '173918995139-3suood033sr5pru46uq4dkgk6rktq05b.apps.googleusercontent.com',
    iosClientId: '173918995139-agaj2djspmuaa4mv18a2lge77n3l7s8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOr9ZRflW21jKV0xMvw8RnVMl9izr_iMI',
    appId: '1:173918995139:ios:4c7ce841b866c708869876',
    messagingSenderId: '173918995139',
    projectId: 'my-chat-e7416',
    databaseURL: 'https://my-chat-e7416-default-rtdb.firebaseio.com',
    storageBucket: 'my-chat-e7416.appspot.com',
    androidClientId: '173918995139-3suood033sr5pru46uq4dkgk6rktq05b.apps.googleusercontent.com',
    iosClientId: '173918995139-agaj2djspmuaa4mv18a2lge77n3l7s8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO4Tdc0F_yVPnIr6crcM4rWVOQ1GfkPe4',
    appId: '1:173918995139:web:b194196ee3a048f0869876',
    messagingSenderId: '173918995139',
    projectId: 'my-chat-e7416',
    authDomain: 'my-chat-e7416.firebaseapp.com',
    databaseURL: 'https://my-chat-e7416-default-rtdb.firebaseio.com',
    storageBucket: 'my-chat-e7416.appspot.com',
    measurementId: 'G-SX4XELQN8H',
  );
}
